
project_id = "vxkzrgsseeiuamimxiih"

[storage]
[[storage.buckets]]
name = "car-images"
public = true
file_size_limit = "10MB" 
allowed_mime_types = ["image/png", "image/jpeg", "image/jpg", "image/gif"]

[[storage.buckets]]
name = "blog_images"
public = true
file_size_limit = "5MB"
