
project_id = "vxkzrgsseeiuamimxiih"

[storage]
[[storage.buckets]]
name = "car-images"
public = true
file_size_limit = "10MB" 

[[storage.buckets]]
name = "blog_images"
public = true
file_size_limit = "5MB"
